CREATE TABLE [wptracker].[Phones] (
    [id]                   BIGINT         IDENTITY (1, 1) NOT NULL,
    [Make]                 NVARCHAR (50)  NOT NULL,
    [Model]                NVARCHAR (50)  NOT NULL,
    [ProcessorSpeed]       NVARCHAR (50)  NULL,
    [Dimensions]           NVARCHAR (50)  NULL,
    [Weight]               NVARCHAR (50)  NULL,
    [RAM]                  NVARCHAR (50)  NULL,
    [Storage]              NVARCHAR (50)  NULL,
    [BatterySize]          NVARCHAR (50)  NULL,
    [TalkTime]             NVARCHAR (50)  NULL,
    [StandbyTime]          NVARCHAR (50)  NULL,
    [DisplayType]          NVARCHAR (50)  NULL,
    [Resolution]           NVARCHAR (50)  NULL,
    [DisplaySize]          NVARCHAR (50)  NULL,
    [RearCamera]           NVARCHAR (50)  NULL,
    [FrontCamera]          NVARCHAR (50)  NULL,
    [MinOS]                NVARCHAR (50)  NULL,
    [MaxOS]                NVARCHAR (50)  NULL,
    [NFC]                  BIT            NULL,
    [Notes]                NVARCHAR (MAX) NULL,
    [Publish]              BIT            NOT NULL,
    [FullName]             NVARCHAR (50)  NULL,
    [Date]                 NVARCHAR (50)  NULL,
    [Colors]               NVARCHAR (MAX) NULL,
    [Sensors]              NVARCHAR (MAX) NULL,
    [SIMCardType]          NVARCHAR (MAX) NULL,
    [ChargingConnectors]   NVARCHAR (MAX) NULL,
    [AVConnectors]         NVARCHAR (MAX) NULL,
    [SystemConnectors]     NVARCHAR (MAX) NULL,
    [USBVersion]           NVARCHAR (MAX) NULL,
    [BluetoothVersion]     NVARCHAR (MAX) NULL,
    [BluetoothProfiles]    NVARCHAR (MAX) NULL,
    [WiFiVersion]          NVARCHAR (MAX) NULL,
    [WiFiSecurityModes]    NVARCHAR (MAX) NULL,
    [WirelessConnectivity] NVARCHAR (MAX) NULL,
    [GSMTypes]             NVARCHAR (MAX) NULL,
    [GSMUpload]            NVARCHAR (MAX) NULL,
    [GSMDownload]          NVARCHAR (MAX) NULL,
    [LTETypes]             NVARCHAR (MAX) NULL,
    [LTEUpload]            NVARCHAR (MAX) NULL,
    [LTEDownload]          NVARCHAR (MAX) NULL,
    [WCDMATypes]           NVARCHAR (MAX) NULL,
    [WCDMAUpload]          NVARCHAR (MAX) NULL,
    [WCDMADownload]        NVARCHAR (MAX) NULL,
    [BatteryVoltage]       NVARCHAR (MAX) NULL,
    [RemoveableBattery]    BIT            NULL,
    [MaxMusicPlayback]     NVARCHAR (MAX) NULL,
    [MaxVideoPlayback]     NVARCHAR (MAX) NULL,
    [MaxWiFiTime]          NVARCHAR (MAX) NULL,
    [ProcessorName]        NVARCHAR (MAX) NULL,
    [ProcessorType]        NVARCHAR (MAX) NULL,
    [RearAperture]         NVARCHAR (MAX) NULL,
    [RearFocalLength]      NVARCHAR (MAX) NULL,
    [RearMinFocusRange]    NVARCHAR (MAX) NULL,
    [FlashType]            NVARCHAR (MAX) NULL,
    [FlashOperatingRange]  NVARCHAR (MAX) NULL,
    [FrontResolution]      NVARCHAR (MAX) NULL,
    [FrontAperture]        NVARCHAR (MAX) NULL,
    [DeviceGeneration]     NVARCHAR (MAX) NULL,
    PRIMARY KEY CLUSTERED ([id] ASC)
);

